debug: false

server:
  port: 8083
  error:
    include-message: always
    whitelabel:
      enabled: false
  servlet:
    encoding:
      charset: utf-8
    context-path: /

spring:
  application:
    name: JM Spring Boot Security Bootstrap
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbname
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hbm2ddl:
          charset_name: UTF-8
    open-in-view: false
  devtools:
    livereload:
      enabled: true
    add-properties: true
  web:
    locale: ru_RU
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    root: warn
  charset:
    console: UTF-8

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: beans, mappings
